export const SET_USER_DETAILS_LOADING = "SET_USER_DETAILS_LOADING";
export const SET_USER_DETAILS_SUCCESS = "SET_USER_DETAILS_SUCCESS";
export const SET_USER_DETAILS_ERROR = "SET_USER_DETAILS_ERROR";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
