export const SET_LOGIN_LOADING = "SET_LOGIN_LOADING";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";

export const SET_USER_DETAILS_LOADING = "SET_USER_DETAILS_LOADING";
export const SET_USER_DETAILS_SUCCESS = "SET_USER_DETAILS_SUCCESS";
export const SET_USER_DETAILS_ERROR = "SET_USER_DETAILS_ERROR";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
