export const SERVICE_REQUEST_RECEIVED_LOADING =
  "SERVICE_REQUEST_RECEIVED_LOADING";
export const SERVICE_REQUEST_RECEIVED_SUCCESS =
  "SERVICE_REQUEST_RECEIVED_SUCCESS";
export const SERVICE_REQUEST_RECEIVED_ERROR = "SERVICE_REQUEST_RECEIVED_ERROR";
